"""Scan configuration constants shared across scanner modules."""
import os

SCAN_PROFILES = {
    'stealth': {
        'jitter': (5, 30),
        'batch_size': 1,
        'passive_only': True,
        'ua_rotate': True,
        'rate_limit': True,
    },
    'quick': {
        'jitter': (0, 0.2),
        'batch_size': 15,
        'passive_only': False,
        'ua_rotate': True,
        'rate_limit': False,
        'skip_modules': ['Dark Web', 'Supply Chain', 'Crypto Miner', 'DDoS Readiness',
                         'Bot Detection', 'Firewall Bypass', 'Clickjacking Deep',
                         'DNS Rebinding', 'Subdomain Takeover Verify', 'Container Security',
                         'Kubernetes Security', 'Checkov', 'Trivy', 'Grype',
                         'OSV Dependencies', 'Git Leaks', 'Credential Stuffing', '2FA Bypass'],
    },
    'balanced': {
        'jitter': (0.3, 1),
        'batch_size': 6,
        'passive_only': False,
        'ua_rotate': True,
        'rate_limit': False,
    },
    'aggressive': {
        'jitter': (0, 0),
        'batch_size': 10,
        'passive_only': False,
        'ua_rotate': False,
        'rate_limit': False,
    },
    'bughunter': {
        'jitter': (0, 0),
        'batch_size': 12,
        'passive_only': False,
        'ua_rotate': False,
        'rate_limit': False,
        'max_crawl_depth': 5,
        'max_crawl_urls': 300,
        'max_js_analysis': 50,
        'sensitive_path_checks': 80,
        'param_discovery': True,
        'js_endpoint_extraction': True,
        'graphql_introspection': True,
        'race_condition_tests': True,
        'idor_deep_test': True,
        'mass_assignment_test': True,
        'ssrf_blind_test': True,
        'xxe_out_of_band': True,
        'cache_poisoning_test': True,
        'websocket_test': True,
        'prototype_pollution': True,
        'deserialization_test': True,
        'host_header_injection': True,
        'open_redirect_deep': True,
        'cors_misconfig_test': True,
        'jwt_algorithm_confusion': True,
        'oauth_redirect_bypass': True,
        'csrf_token_analysis': True,
        'clickjacking_test': True,
        'http_smuggling_test': True,
        'dns_rebinding_test': True,
        'subdomain_takeover_test': True,
        'secret_in_js_test': True,
        'api_abuse_test': True,
    },
}

SCAN_HARD_LIMIT = 7200  # 2 hours — allows bughunter profile to complete all modules

ATTACK_MODULE_NAMES = {
    'SQLi Manual', 'XSS Manual', 'SSRF Manual', 'Command Injection',
    'SSTI', 'File Inclusion LFI/RFI', 'SQLMap', 'Dalfox XSS',
    'Open Redirect Manual', 'XXE Injection', 'Advanced XXE',
    'Cache Poisoning', 'Insecure Deserialization', 'NoSQL Injection',
    'LDAP Injection', 'File Upload', 'Header Injection', 'Prototype Pollution',
    'Session Fixation', 'JWT Advanced', 'API Abuse',
    'IDOR Deep Test', 'Mass Assignment', 'Race Condition',
    'Host Header Injection', 'HTTP Smuggle', 'WebSocket Testing',
    'DNS Rebinding', 'Subdomain Takeover Verify', 'CSRF Testing',
    '2FA Bypass', 'Credential Stuffing', 'OAuth Attack',
    'GraphQL Advanced', 'Clickjacking Deep',
}

ADAPTIVE_ROUTING = os.environ.get('ADAPTIVE_ROUTING', '0') == '1'

DYNAMIC_ONLY_MODULES = {
    'SQLMap', 'SQLi Manual', 'SQLi Deep Test',
    'XSS Manual', 'Dalfox XSS',
    'SSRF Manual',
    'Command Injection',
    'SSTI',
    'XXE Injection', 'Advanced XXE',
    'NoSQL Injection', 'LDAP Injection',
    'CSRF Testing',
    'Auth Testing',
    'JWT Testing', 'JWT Advanced',
    'OAuth Testing', 'OAuth Attack',
    'Session Fixation',
    'Mass Assignment', 'Race Condition', 'IDOR', 'IDOR Deep Test',
    'Business Logic',
    'Insecure Deserialization', 'Prototype Pollution',
    'File Inclusion LFI/RFI', 'File Upload',
    'Cache Poisoning', 'HTTP Smuggle',
    'Header Injection', 'Host Header Injection',
    'Open Redirect Manual',
    'WebSocket Testing',
    'Arjun Params',
    'API Security', 'API Abuse', 'GraphQL Security', 'GraphQL Advanced',
    'DNS Rebinding',
    'Unauth Endpoint Analysis',
    'Token & Secret Hunt',
    'Credential Stuffing', '2FA Bypass',
    'Clickjacking Deep',
}
